export const STORE = {
  name: 'Seu Nenê',
  fullName: 'Restaurante e Pizzaria Seu Nenê',
  phone: '(43) 3432-5222',
  phoneHref: 'tel:+554334325222',
  mapsHref: 'https://www.google.com/maps/search/?api=1&query=Av.%20Dr.%20Get%C3%BAlio%20Vargas%2C%20619%2C%20Jandaia%20do%20Sul%2C%20PR',
  address: 'Av. Dr. Getúlio Vargas, 619 · Centro · Jandaia do Sul, PR',
  rating: '4,6',
  delivery: '60–90 min',
  minimum: 30,
  orderHours: 'Terça a domingo · 18h–23h',
}

const p = (id, name, category, description, sizes, badge='') => ({id,name,category,description,sizes,badge})

export const PRODUCTS = [
  p('s01','À moda','Pizzas salgadas','Molho de tomate, muçarela, presunto, catupiry, milho, palmito, ervilha, champignon, ovos, bacon e orégano.',{Pequena:48.9,Média:67.9,Grande:81.9,Gigante:99.9}),
  p('s02','Abobrinha e cream cheese','Pizzas salgadas','Molho de tomate, muçarela, cream cheese, abobrinha grelhada, lâminas de alho e orégano.',{Pequena:44.9,Média:61.9,Grande:73.9,Gigante:92.9},'SEM CARNE'),
  p('s03','Alho e óleo','Pizzas salgadas','Molho de tomate, muçarela, alho frito, azeite e orégano.',{Pequena:44.9,Média:61.9,Grande:73.9,Gigante:92.9},'SEM CARNE'),
  p('s04','Atum','Pizzas salgadas','Molho de tomate, muçarela, atum, cebola e orégano.',{Pequena:44.9,Média:61.9,Grande:73.9,Gigante:92.9}),
  p('s05','Bacon','Pizzas salgadas','Molho de tomate, muçarela, bacon e orégano.',{Pequena:44.9,Média:61.9,Grande:73.9,Gigante:92.9}),
  p('s06','Baiana','Pizzas salgadas','Molho de tomate, muçarela, presunto, calabresa, pimenta, pimentão e orégano.',{Pequena:44.9,Média:61.9,Grande:73.9,Gigante:92.9}),
  p('s07','Brócolis','Pizzas salgadas','Molho de tomate, muçarela, brócolis, bacon, alho frito e orégano.',{Pequena:44.9,Média:61.9,Grande:73.9,Gigante:92.9}),
  p('s08','Calabresa','Pizzas salgadas','Molho de tomate, muçarela, calabresa, cebola e orégano.',{Pequena:44.9,Média:61.9,Grande:73.9,Gigante:92.9}),
  p('s09','Camarão','Pizzas salgadas','Molho de tomate, muçarela, camarão, pimentão, cebola e orégano.',{Pequena:49.9,Média:67.9,Grande:89.9,Gigante:106.9}),
  p('s10','Caprese','Pizzas salgadas','Molho de tomate, muçarela, tomate, muçarela de búfala, manjericão e orégano.',{Pequena:48.9,Média:67.9,Grande:81.9,Gigante:99.9},'SEM CARNE'),
  p('s11','Escarola com bacon','Pizzas salgadas','Molho de tomate, muçarela, escarola, alho, bacon e orégano.',{Pequena:44.9,Média:61.9,Grande:73.9,Gigante:92.9}),
  p('s12','Frango com catupiry','Pizzas salgadas','Molho de tomate, muçarela, frango desfiado, catupiry e orégano.',{Pequena:48.9,Média:67.9,Grande:81.9,Gigante:99.9}),
  p('s13','Linguiça apimentada c/ provolone','Pizzas salgadas','Molho de tomate, muçarela, provolone, linguiça apimentada, cebola, cebolinha e orégano.',{Pequena:48.9,Média:67.9,Grande:81.9,Gigante:99.9}),
  p('s14','Lombinho','Pizzas salgadas','Molho de tomate, muçarela, lombo canadense grelhado, catupiry e orégano.',{Pequena:48.9,Média:67.9,Grande:81.9,Gigante:99.9}),
  p('s15','Marguerita','Pizzas salgadas','Molho de tomate, muçarela, tomate, manjericão e orégano.',{Pequena:44.9,Média:61.9,Grande:73.9,Gigante:92.9},'SEM CARNE'),
  p('s16','Milho com bacon','Pizzas salgadas','Molho de tomate, muçarela, milho, bacon e orégano.',{Pequena:44.9,Média:61.9,Grande:73.9,Gigante:92.9}),
  p('s17','Muçarela','Pizzas salgadas','Molho de tomate, muçarela, tomate e orégano.',{Pequena:44.9,Média:61.9,Grande:73.9,Gigante:92.9},'SEM CARNE'),
  p('s18','Napolitana','Pizzas salgadas','Molho de tomate, muçarela, presunto, tomate e orégano.',{Pequena:44.9,Média:61.9,Grande:73.9,Gigante:92.9}),
  p('s19','Palmito','Pizzas salgadas','Molho de tomate, muçarela, palmito, tomate e orégano.',{Pequena:44.9,Média:61.9,Grande:73.9,Gigante:92.9},'SEM CARNE'),
  p('s20','Pepperoni','Pizzas salgadas','Molho de tomate, muçarela, pepperoni, cebola e orégano.',{Pequena:49.9,Média:67.9,Grande:89.9,Gigante:106.9}),
  p('s21','Picanha','Pizzas salgadas','Molho de tomate, muçarela, picanha grelhada, alho frito e orégano.',{Pequena:49.9,Média:67.9,Grande:89.9,Gigante:106.9}),
  p('s22','Pizzaiolo','Pizzas salgadas','Molho de tomate, muçarela, calabresa, tomate picado, creme de leite e orégano.',{Pequena:44.9,Média:61.9,Grande:73.9,Gigante:92.9}),
  p('s23','Portuguesa','Pizzas salgadas','Molho de tomate, muçarela, presunto, cebola, ervilha, pimentão, ovos e orégano.',{Pequena:48.9,Média:67.9,Grande:81.9,Gigante:99.9}),
  p('s24','Presunto parma com rúcula','Pizzas salgadas','Molho de tomate, muçarela, parmesão, presunto de parma, rúcula e orégano.',{Pequena:49.9,Média:67.9,Grande:89.9,Gigante:106.9}),
  p('s25','Quatro queijos','Pizzas salgadas','Molho de tomate, muçarela, catupiry, parmesão, provolone e orégano.',{Pequena:48.9,Média:67.9,Grande:81.9,Gigante:99.9},'SEM CARNE'),
  p('s26','Rúcula','Pizzas salgadas','Molho de tomate, muçarela, tomate seco, rúcula e orégano.',{Pequena:44.9,Média:61.9,Grande:73.9,Gigante:92.9},'SEM CARNE'),
  p('s27','Seu Nenê','Pizzas salgadas','Molho de tomate, muçarela, frango desfiado, catupiry, palmito, calabresa e orégano.',{Pequena:48.9,Média:67.9,Grande:81.9,Gigante:99.9},'DA CASA'),
  p('s28','Strogonoff de boi','Pizzas salgadas','Molho de tomate, muçarela, strogonoff de boi, batata palha e orégano.',{Pequena:49.9,Média:67.9,Grande:89.9,Gigante:106.9}),
  p('s29','Vegetariana','Pizzas salgadas','Molho de tomate, muçarela, palmito, ervilha, tomate e orégano.',{Pequena:44.9,Média:61.9,Grande:73.9,Gigante:92.9},'SEM CARNE'),

  p('d01','Banana','Pizzas doces','Um pouco de muçarela, leite condensado, banana e canela.',{Pequena:39.9,Média:51.9,Grande:67.9,Gigante:78.9}),
  p('d02','Chocolate','Pizzas doces','Um pouco de muçarela e chocolate ao leite.',{Pequena:39.9,Média:51.9,Grande:67.9,Gigante:78.9}),
  p('d03','Confete','Pizzas doces','Um pouco de muçarela, chocolate ao leite ou branco e confetes.',{Pequena:39.9,Média:51.9,Grande:67.9,Gigante:78.9}),
  p('d04','Pé de moleque','Pizzas doces','Um pouco de muçarela, doce de leite, amendoim e paçoca.',{Pequena:39.9,Média:51.9,Grande:67.9,Gigante:78.9}),
  p('d05','Romeu e Julieta','Pizzas doces','Um pouco de muçarela, goiabada e requeijão.',{Pequena:39.9,Média:51.9,Grande:57.9,Gigante:78.9}),
  p('d06','Nutella','Pizzas doces','Um pouco de muçarela e Nutella.',{Pequena:44.9,Média:55.9,Grande:72.9,Gigante:83.9}),
  p('d07','Sensação','Pizzas doces','Um pouco de muçarela, chocolate e morango.',{Pequena:44.9,Média:55.9,Grande:72.9,Gigante:83.9}),
  p('d08','Chocolate branco','Pizzas doces','Um pouco de muçarela e chocolate branco.',{Pequena:39.9,Média:51.9,Grande:57.9,Gigante:78.9}),

  p('c01','À moda','Calzones','Molho de tomate, muçarela, presunto, catupiry, milho, palmito, ervilha, champignon, ovos, bacon, azeitona preta e orégano.',{Médio:59.9,Grande:72.9}),
  p('c02','Bacon','Calzones','Molho de tomate, muçarela, bacon e orégano.',{Médio:55.9,Grande:67.9}),
  p('c03','Calabresa','Calzones','Molho de tomate, muçarela, calabresa, cebola e orégano.',{Médio:55.9,Grande:67.9}),
  p('c04','Frango com catupiry','Calzones','Molho de tomate, muçarela, frango desfiado, catupiry e orégano.',{Médio:59.9,Grande:72.9}),
  p('c05','Linguiça apimentada com provolone','Calzones','Molho de tomate, muçarela, provolone, linguiça apimentada, cebola, cebolinha e orégano.',{Médio:59.9,Grande:72.9}),
  p('c06','Portuguesa','Calzones','Molho de tomate, muçarela, presunto, cebola, ervilha, pimentão, ovos e orégano.',{Médio:59.9,Grande:72.9}),
  p('c07','Quatro queijos','Calzones','Molho de tomate, muçarela, catupiry, parmesão, provolone e orégano.',{Médio:59.9,Grande:72.9}),
  p('c08','Sensação','Calzones','Chocolate e morango.',{Médio:59.9,Grande:72.9}),

  p('p01','Escondidinho carne de sol','Porções','Porção de 1 kg de escondidinho de carne de sol.',{Inteira:55.9}),
  p('p02','Strogonoff','Porções','Porção de 500 g de strogonoff de boi, acompanha batata palha.',{Inteira:39.9}),
  p('p03','Frango a passarinho','Porções','Porção para compartilhar.',{Inteira:55.9}),
  p('p04','Fritas turbinadas','Porções','Porção de fritas turbinadas.',{Inteira:43.9}),
  p('p05','Kibe frito','Porções','Temperado com hortelã.',{Inteira:44.9}),
  p('p06','Torresminho BH','Porções','Acompanha molho de pimenta da casa.',{Inteira:63.9}),

  p('r01','Filé à parmegiana','Refeições','Carne de boi ou frango, molho de tomate, muçarela e manjericão; acompanha arroz e fritas.',{Único:155}),
  p('r02','Marmitex G com bisteca de porco','Refeições','Bisteca de porco, arroz, feijão, batata frita, ovo frito e salada.',{Único:29.9}),
  p('r03','Marmitex G com frango','Refeições','Filé de frango, arroz, feijão, batata frita, ovo frito e salada.',{Único:29.9}),
  p('r04','Marmitex M com bisteca de porco','Refeições','Bisteca de porco, arroz, feijão, batata frita, ovo frito e salada.',{Único:26.9}),
  p('r05','Marmitex M com frango','Refeições','Filé de frango, arroz, feijão, batata frita, ovo frito e salada.',{Único:26.9}),

  p('b01','Citrus','Refrigerantes','Lata.',{Único:6.9}),
  p('b02','Coca-Cola lata sem açúcar','Refrigerantes','Lata.',{Único:5.9}),
  p('b03','Coca-Cola lata','Refrigerantes','Lata.',{Único:5.9}),
  p('b04','Coca-Cola PET 1 litro','Refrigerantes','Garrafa PET 1 L.',{Único:11}),
  p('b05','Coca-Cola PET 2 litros','Refrigerantes','Garrafa PET 2 L.',{Único:13}),
  p('b06','Coca-Cola PET 600 ml','Refrigerantes','Garrafa PET 600 ml.',{Único:7.9}),
  p('b07','Fanta laranja lata','Refrigerantes','Lata.',{Único:5.9}),
  p('b08','Sprite lata 350 ml','Refrigerantes','Lata 350 ml.',{Único:5.9}),

  p('j01','Laranja','Sucos','Suco 500 ml.',{'500 ml':16.9}),
  p('j02','Abacaxi','Sucos','Suco 500 ml.',{'500 ml':16.9}),
  p('j03','Abacaxi com hortelã','Sucos','Suco 500 ml.',{'500 ml':16.9}),
  p('j04','Morango','Sucos','Suco 500 ml.',{'500 ml':16.9}),
]

export const CATEGORIES = ['Pizzas salgadas','Pizzas doces','Calzones','Porções','Refeições','Refrigerantes','Sucos']
